$(function(){
		$('#uname').on('input',function(){
			$.ajax({
				data:{'uname':$(this).val()},
				type:'POST',
				url:'/webproject/check.do',
				success:function(data){
					if(data=="0"){
						$('#sp2').html('用户名不能为空');
						$('#sp2').css('color','red');
					}
					if(data=="1"){
						$('#sp2').html('用户名已存在');
						$('#sp2').css('color','red');
					}
					if(data=="2"){
						$('#sp2').html('用户名可以使用');
						$('#sp2').css('color','green');
					}
				}
			});
		})
		$('#uemail').on('input',function(){
			$.ajax({
				data:{'uemail':$(this).val()},
				type:'POST',
				url:'/webproject/checkuemail.do',
				success:function(data){
					if(data=="0"){
						$('#sp1').html('邮箱不能为空');
						$('#sp1').css('color','red');
					}
					if(data=="1"){
						$('#sp1').html('邮箱已存在');
						$('#sp1').css('color','red');
					}
					if(data=="2"){
						$('#sp1').html('恭喜，可以使用');
						$('#sp1').css('color','green');
					}
					if(data=="3"){
						$('#sp1').html('邮箱格式错误');
						$('#sp1').css('color','red');
					}
				}
			});
		})
		$('#upassword').on('input',function(){
			$.ajax({
				data:{'upassword':$(this).val()},
				type:'POST',
				url:"/webproject/checkupassword.do",
				success:function(data){
					if(data=="1"){
						$('#fn').html('请输入正确格式的密码')
						$('#fn').css('color','red');
					}
					if(data=="2"){
						$('#fn').html('密码强度弱')
						$('#fn').css('color','red');
					}
					if(data=="3"){
						$('#fn').html('密码强度强')
						$('#fn').css('color','green');
					}
					if(data=="4"){
						$('#fn').html('密码强度超强')
						$('#fn').css('color','green');
					}
				}
			})
		})
	})